on:
  workflow_call:
    inputs:
      model-name:
        required: true
        type: string
      model-source:
        required: true
        type: string
      upload:
        type: boolean
        default: false

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
      - run: uv sync # TODO: cache uv env (does setup-uv do that already automatically?)

      - run: uv run python -m immich_model_exporter.main export "${{ inputs.model-name }}" "${{ inputs.model-source }}"

      # TODO: upload-artifact the exported model

  # When doing benchmarking, that goes here
  # Download the exported artifact, and upload an artifact with the benchmark result to be used below

  upload:
    if: ${{ inputs.upload }}
    runs-on: ubuntu-latest
    needs: export
    steps:
      - run: echo "And upload the combined result!"
        # download both artifacts, combine, and upload to HF
