"""Checker-only types for the onnxscript eDSL as _dsl.py uses it. Never imported at runtime.

onnxscript's generated opset stubs describe ONNX operator schemas (tensor-typed inputs,
Optional-heavy returns), not script mode's tracing reality where Python scalars and lists
autocast to constant tensors and every traced value is interchangeable. These declarations
type that reality instead: one tensor type with operators, ops accepting Python operands.
"""

from collections.abc import Sequence
from typing import Any, Callable

from onnxscript.values import OnnxFunction

class TENSOR:
    def __class_getitem__(cls, shape: Any) -> type[TENSOR]: ...
    def __add__(self, other: TensorLike) -> FLOAT: ...
    def __radd__(self, other: TensorLike) -> FLOAT: ...
    def __sub__(self, other: TensorLike) -> FLOAT: ...
    def __rsub__(self, other: TensorLike) -> FLOAT: ...
    def __mul__(self, other: TensorLike) -> FLOAT: ...
    def __rmul__(self, other: TensorLike) -> FLOAT: ...
    def __truediv__(self, other: TensorLike) -> FLOAT: ...
    def __rtruediv__(self, other: TensorLike) -> FLOAT: ...
    def __neg__(self) -> FLOAT: ...
    def __getitem__(self, index: Any) -> FLOAT: ...

class FLOAT(TENSOR): ...
class UINT8(TENSOR): ...

TensorLike = TENSOR | float | int | Sequence[int]

class _Opset:
    def Cast(self, x: TensorLike, *, to: int) -> FLOAT: ...
    def Concat(self, *xs: TensorLike, axis: int) -> FLOAT: ...
    def Constant(self, *, value: Any = ..., value_ints: Sequence[int] = ..., value_float: float = ...) -> FLOAT: ...
    def Gather(self, data: TensorLike, indices: TensorLike, *, axis: int = ...) -> FLOAT: ...
    def GridSample(
        self,
        x: TensorLike,
        grid: TensorLike,
        *,
        mode: str = ...,
        padding_mode: str = ...,
        align_corners: int = ...,
    ) -> FLOAT: ...
    def MatMul(self, a: TensorLike, b: TensorLike) -> FLOAT: ...
    def Max(self, *xs: TensorLike) -> FLOAT: ...
    def Neg(self, x: TensorLike) -> FLOAT: ...
    def ReduceL2(self, x: TensorLike, axes: TensorLike = ..., *, keepdims: int = ...) -> FLOAT: ...
    def ReduceSum(self, x: TensorLike, axes: TensorLike = ..., *, keepdims: int = ...) -> FLOAT: ...
    def Reshape(self, x: TensorLike, shape: TensorLike, *, allowzero: int = ...) -> FLOAT: ...
    def Transpose(self, x: TensorLike, *, perm: Sequence[int]) -> FLOAT: ...

op: _Opset

def script(*, default_opset: Any = ...) -> Callable[[Callable[..., Any]], OnnxFunction[Any, Any]]: ...
